/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import controlas.Dicionario;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import model.Palavra;
import util.ConexaoBD;

/**
 *
 * @author artur
 */
public class TelaPrincipal
        extends javax.swing.JFrame
{

    private Dicionario dicionario;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal()
    {
        dicionario = new Dicionario();
        
        initComponents();
        
        setTitle( "Meu Dicionário!" );
        addWindowListener( new WindowAdapter()
        {
            @Override
            public void windowClosing( WindowEvent e )
            {
                ConexaoBD.getInstance().shutDown();
            }
        });
        carregaTabela( dicionario.getPalavras() );
    }

    private void carregaTabela( ArrayList<Palavra> palavras )
    {
        tblPalabras.setBackground( Color.WHITE );
        tblPalabras.setModel( new AbstractTableModel() 
        {
            // título das colunas
            public String getColumnName( int column )
            {
                switch ( column )
                {
                    case 0:
                        return "Código";
                    case 1:
                        return "Nome";
                    case 2:
                        return "Significado";
                    case 3:
                        return "Versão";
                    default:
                        return "";
                }
            }
            
            public int getColumnCount() // quantidade de colunas
            {
                return 4;
            }
            
            public int getRowCount() // quantidade de linhas
            {
                return palavras.size();
            }
            
            public Object getValueAt( int rowIndex, int columnIndex ) // valor das colunas
            {
                Palavra palavra = palavras.get( rowIndex );
                
                switch ( columnIndex )
                {
                    case 0:
                        return palavra.codigo;
                    case 1:
                        return palavra.nome;
                    case 2:
                        return palavra.significado;
                    case 3:
                        return palavra.versao;
                    default:
                        return "";
                }
            }

        });
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JTabbedPane();
        tabCadastro = new javax.swing.JPanel();
        lbCodigo = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbSignificado = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSignificado = new javax.swing.JTextArea();
        btnAdicionar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        tabConsulta = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPalabras = new javax.swing.JTable();
        lbConsulta = new javax.swing.JLabel();
        txtConsulta = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                panelStateChanged(evt);
            }
        });

        lbCodigo.setText("Códgio:");

        lbNome.setText("Nome:");

        lbSignificado.setText("Significado:");

        txtCodigo.setEditable(false);

        txtSignificado.setColumns(20);
        txtSignificado.setRows(5);
        jScrollPane1.setViewportView(txtSignificado);

        btnAdicionar.setText("Salvar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabCadastroLayout = new javax.swing.GroupLayout(tabCadastro);
        tabCadastro.setLayout(tabCadastroLayout);
        tabCadastroLayout.setHorizontalGroup(
            tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCadastroLayout.createSequentialGroup()
                        .addComponent(lbSignificado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCadastroLayout.createSequentialGroup()
                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tabCadastroLayout.createSequentialGroup()
                                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCodigo)
                                    .addComponent(lbNome))
                                .addGap(18, 18, 18)
                                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tabCadastroLayout.createSequentialGroup()
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtNome)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabCadastroLayout.createSequentialGroup()
                                .addComponent(btnSair)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdicionar)))
                        .addGap(14, 14, 14))
                    .addGroup(tabCadastroLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        tabCadastroLayout.setVerticalGroup(
            tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastroLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbSignificado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCadastroLayout.createSequentialGroup()
                        .addComponent(btnSair)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCadastroLayout.createSequentialGroup()
                        .addComponent(btnAdicionar)
                        .addGap(16, 16, 16))))
        );

        lbCodigo.getAccessibleContext().setAccessibleName("Código");

        panel.addTab("Cadastro", tabCadastro);

        tblPalabras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPalabras);

        lbConsulta.setText("Filtro:");

        txtConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConsultaKeyTyped(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabConsultaLayout = new javax.swing.GroupLayout(tabConsulta);
        tabConsulta.setLayout(tabConsultaLayout);
        tabConsultaLayout.setHorizontalGroup(
            tabConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(tabConsultaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbConsulta)
                .addGap(18, 18, 18)
                .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabConsultaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluir)
                .addGap(18, 18, 18)
                .addComponent(btnEditar)
                .addGap(22, 22, 22))
        );
        tabConsultaLayout.setVerticalGroup(
            tabConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabConsultaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tabConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConsulta)
                    .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addGap(27, 27, 27))
        );

        panel.addTab("Consulta", tabConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel.getAccessibleContext().setAccessibleName("Geral");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAdicionarActionPerformed
    {//GEN-HEADEREND:event_btnAdicionarActionPerformed
        String nome = txtNome.getText();
        String significado = txtSignificado.getText();

        if ( txtCodigo.getText().isEmpty() )
        {
            Palavra palavra = new Palavra();
            palavra.significado = significado;
            palavra.nome = nome;

            String errors = dicionario.addPalavra( palavra );
            
            if ( errors != null )
            {
                JOptionPane.showMessageDialog( null, errors );
            }

            else
            {
                JOptionPane.showMessageDialog( null, 
                                               "Palavra Cadastrada com sucesso!", "Meu Dicionario", JOptionPane.WARNING_MESSAGE, null  );
                
                limpaCampos();
            }
        }
        
        else
        {
            Palavra p = dicionario.consultarPalavraPorCodigo( Integer.valueOf( txtCodigo.getText() ) );
            p.nome = txtNome.getText();
            p.significado = txtSignificado.getText();
            p.versao += 1;
            
            dicionario.updatePalavra(p);
            JOptionPane.showMessageDialog( null, 
                                               "Palavra alterada com sucesso!", "Meu Dicionario", JOptionPane.WARNING_MESSAGE, null  );
            
            limpaCampos();   
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void limpaCampos()
    {
        txtNome.setText( "" );
        txtSignificado.setText( "" );
        txtCodigo.setText( "" );
    }
    
    private void panelStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_panelStateChanged
    {//GEN-HEADEREND:event_panelStateChanged
        if ( panel.getSelectedIndex() == 1 )
        {
            carregaTabela( dicionario.consultarPalavra( txtConsulta.getText() ) );
        }
    }//GEN-LAST:event_panelStateChanged

    private void txtConsultaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtConsultaKeyTyped
    {//GEN-HEADEREND:event_txtConsultaKeyTyped
        
        carregaTabela( dicionario.consultarPalavra( txtConsulta.getText() ) );
        
    }//GEN-LAST:event_txtConsultaKeyTyped

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExcluirActionPerformed
    {//GEN-HEADEREND:event_btnExcluirActionPerformed
        int index = tblPalabras.getSelectedRow();
       
        if ( index != -1 )
        {
            if ( JOptionPane.showConfirmDialog( null, "Tem certeza?" ) == JOptionPane.YES_OPTION )
            {           
                int codigo = Integer.valueOf(
                        String.valueOf( 
                                tblPalabras.getModel().getValueAt( index, 0 )
                        ) );

                Palavra p = dicionario.consultarPalavraPorCodigo( codigo );

                if ( p != null )
                {
                    dicionario.removePalavra( p );

                    carregaTabela( dicionario.consultarPalavra( txtConsulta.getText() ) );
                }
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEditarActionPerformed
    {//GEN-HEADEREND:event_btnEditarActionPerformed
        int index = tblPalabras.getSelectedRow();
       
        if ( index != -1 )
        {
            int codigo = Integer.valueOf(
                    String.valueOf( 
                            tblPalabras.getModel().getValueAt( index, 0 )
                    ) );

            Palavra p = dicionario.consultarPalavraPorCodigo( codigo );

            if ( p != null )
            {
               txtCodigo.setText( String.valueOf( p.codigo ) );
               txtNome.setText( p.nome );
               txtSignificado.setText( p.significado );
               
               panel.setSelectedIndex( 0 );
            }
        }
        
        else
        {
            JOptionPane.showMessageDialog( null, "Selecione uma linha!" );
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSairActionPerformed
    {//GEN-HEADEREND:event_btnSairActionPerformed
        ConexaoBD.getInstance().shutDown();
        
        System.exit( 0 );
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Nimbus".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( TelaPrincipal.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( TelaPrincipal.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( TelaPrincipal.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( TelaPrincipal.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            public void run()
            {
                new TelaPrincipal().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbConsulta;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbSignificado;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JPanel tabCadastro;
    private javax.swing.JPanel tabConsulta;
    private javax.swing.JTable tblPalabras;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtConsulta;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextArea txtSignificado;
    // End of variables declaration//GEN-END:variables
}
